import './globals.css';
import { Inter } from 'next/font/google';
import { Session } from 'next-auth';
import Providers from '../components/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  ...props
}: {
  children: React.ReactNode;
  session: Session;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={props.session}>{children}</Providers>
      </body>
    </html>
  );
}
